# Generated by Django 5.2 on 2025-05-10 12:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ComputerDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cpu",
                    models.CharField(
                        help_text="Процессор", max_length=255, verbose_name="Процессор"
                    ),
                ),
                (
                    "ram",
                    models.CharField(
                        help_text="Оперативная память",
                        max_length=255,
                        verbose_name="Оперативная память",
                    ),
                ),
                (
                    "storage",
                    models.CharField(
                        help_text="Накопитель (SSD/HDD)",
                        max_length=255,
                        verbose_name="Накопитель",
                    ),
                ),
                (
                    "has_keyboard",
                    models.BooleanField(default=True, help_text="Есть ли клавиатура"),
                ),
                (
                    "has_mouse",
                    models.BooleanField(default=True, help_text="Есть ли мышь"),
                ),
                (
                    "monitor_size",
                    models.CharField(
                        blank=True,
                        help_text="Размер монитора (если есть)",
                        max_length=50,
                        verbose_name="Размер монитора",
                    ),
                ),
            ],
            options={
                "verbose_name": "Компьютерные характеристики",
                "verbose_name_plural": "Компьютерные характеристики",
            },
        ),
        migrations.CreateModel(
            name="ComputerSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cpu", models.CharField(max_length=255, verbose_name="Процессор")),
                (
                    "ram",
                    models.CharField(max_length=255, verbose_name="Оперативная память"),
                ),
                (
                    "storage",
                    models.CharField(
                        max_length=255, verbose_name="Накопитель (SSD/HDD)"
                    ),
                ),
                (
                    "has_keyboard",
                    models.BooleanField(
                        default=True, verbose_name="Есть ли клавиатура"
                    ),
                ),
                (
                    "has_mouse",
                    models.BooleanField(default=True, verbose_name="Есть ли мышь"),
                ),
                (
                    "monitor_size",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Размер монитора"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Уникальный ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Компьютерная спецификация",
                "verbose_name_plural": "Компьютерные спецификации",
            },
        ),
        migrations.CreateModel(
            name="ContractDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(max_length=100, verbose_name="Номер договора"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="contracts/", verbose_name="Файл договора"
                    ),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, verbose_name="Дата загрузки"),
                ),
            ],
            options={
                "verbose_name": "Договор",
                "verbose_name_plural": "Договора",
            },
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Название оборудования"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="equipment_photos/",
                        verbose_name="Фото оборудования",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "Новое"),
                            ("WORKING", "Требуется ремонт"),
                            ("NEEDS_REPAIR", "Утиль"),
                        ],
                        default="NEW",
                        max_length=20,
                        verbose_name="Состояние",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("inn", models.IntegerField(verbose_name="ИНН")),
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Уникальный ID",
                    ),
                ),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="qr_codes/",
                        verbose_name="QR-код",
                    ),
                ),
            ],
            options={
                "verbose_name": "Оборудование",
                "verbose_name_plural": "Оборудование",
            },
        ),
        migrations.CreateModel(
            name="EquipmentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Название типа оборудования"
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип оборудования",
                "verbose_name_plural": "Типы оборудования",
            },
        ),
        migrations.CreateModel(
            name="MovementHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "moved_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата перемещения"
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "История перемещений",
                "verbose_name_plural": "История перемещений",
            },
        ),
    ]
