# Generated by Django 5.2 on 2025-05-10 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
        ("university", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="computerspecification",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_computer_specifications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_equipment",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="contract",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.contractdocument",
                verbose_name="Договор",
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="equipment",
                to="university.room",
                verbose_name="Кабинет",
            ),
        ),
        migrations.AddField(
            model_name="computerdetails",
            name="equipment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="computer_details",
                to="inventory.equipment",
                verbose_name="Оборудование",
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="equipment",
                to="inventory.equipmenttype",
                verbose_name="Тип оборудования",
            ),
        ),
        migrations.AddField(
            model_name="movementhistory",
            name="equipment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movements",
                to="inventory.equipment",
                verbose_name="Оборудование",
            ),
        ),
        migrations.AddField(
            model_name="movementhistory",
            name="from_room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="moved_out",
                to="university.room",
                verbose_name="Из кабинета",
            ),
        ),
        migrations.AddField(
            model_name="movementhistory",
            name="to_room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="moved_in",
                to="university.room",
                verbose_name="В кабинет",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="computerspecification",
            unique_together={("cpu", "ram", "storage")},
        ),
    ]
