# Generated by Django 5.2 on 2025-05-13 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "Новое"),
                    ("WORKING", "Требуется ремонт"),
                    ("NEEDS_REPAIR", "На утилизацию"),
                ],
                default="NEW",
                max_length=20,
                verbose_name="Состояние",
            ),
        ),
        migrations.CreateModel(
            name="ExtenderChar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ports",
                    models.IntegerField(default=4, verbose_name="Количество портов"),
                ),
                (
                    "length",
                    models.CharField(max_length=50, verbose_name="Длина кабеля"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_extender",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "equipment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extender_char",
                        to="inventory.equipment",
                        verbose_name="Оборудование",
                    ),
                ),
            ],
            options={
                "verbose_name": "Расширитель Char",
                "verbose_name_plural": "Расширители Char",
            },
        ),
        migrations.CreateModel(
            name="ExtenderSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ports",
                    models.IntegerField(default=4, verbose_name="Количество портов"),
                ),
                (
                    "length",
                    models.CharField(max_length=50, verbose_name="Длина кабеля"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="createdspek_extender",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Расширитель Спецификасии",
                "verbose_name_plural": "Расширители Спецификасии",
            },
        ),
        migrations.CreateModel(
            name="PrinterChar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model",
                    models.CharField(max_length=255, verbose_name="Модель принтера"),
                ),
                (
                    "serial_number",
                    models.CharField(max_length=255, verbose_name="Серийный номер"),
                ),
                ("color", models.BooleanField(default=False, verbose_name="Цветной")),
                (
                    "duplex",
                    models.BooleanField(default=False, verbose_name="Дуплексный"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_printer",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "equipment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="printer_char",
                        to="inventory.equipment",
                        verbose_name="Оборудование",
                    ),
                ),
            ],
            options={
                "verbose_name": "Принтер Char",
                "verbose_name_plural": "Принтеры Char",
            },
        ),
        migrations.CreateModel(
            name="PrinterSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model",
                    models.CharField(max_length=255, verbose_name="Модель принтера"),
                ),
                (
                    "serial_number",
                    models.CharField(max_length=255, verbose_name="Серийный номер"),
                ),
                ("color", models.BooleanField(default=False, verbose_name="Цветной")),
                (
                    "duplex",
                    models.BooleanField(default=False, verbose_name="Дуплексный"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="createdspek_printer",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Спецификация принтера",
                "verbose_name_plural": "Спецификации принтеров",
            },
        ),
        migrations.CreateModel(
            name="RouterChar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model",
                    models.CharField(max_length=255, verbose_name="Модель роутера"),
                ),
                (
                    "serial_number",
                    models.CharField(max_length=255, verbose_name="Серийный номер"),
                ),
                (
                    "ports",
                    models.IntegerField(default=4, verbose_name="Количество портов"),
                ),
                (
                    "wifi_standart",
                    models.CharField(max_length=50, verbose_name="Стандарт Wi-Fi"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_router",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "equipment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="router_char",
                        to="inventory.equipment",
                        verbose_name="Оборудование",
                    ),
                ),
            ],
            options={
                "verbose_name": "Роутер Char",
                "verbose_name_plural": "Роутеры Char",
            },
        ),
        migrations.CreateModel(
            name="RouterSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model",
                    models.CharField(max_length=255, verbose_name="Модель роутера"),
                ),
                (
                    "serial_number",
                    models.CharField(max_length=255, verbose_name="Серийный номер"),
                ),
                (
                    "ports",
                    models.IntegerField(default=4, verbose_name="Количество портов"),
                ),
                (
                    "wifi_standart",
                    models.CharField(max_length=50, verbose_name="Стандарт Wi-Fi"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="createdspek_router",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Роутер Спецификасии",
                "verbose_name_plural": "Роутеры Спецификасии",
            },
        ),
        migrations.CreateModel(
            name="TVChar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model",
                    models.CharField(max_length=255, verbose_name="Модель телевизора"),
                ),
                (
                    "serial_number",
                    models.CharField(max_length=255, verbose_name="Серийный номер"),
                ),
                (
                    "screen_size",
                    models.CharField(max_length=50, verbose_name="Размер экрана"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_tv",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "equipment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tv_char",
                        to="inventory.equipment",
                        verbose_name="Оборудование",
                    ),
                ),
            ],
            options={
                "verbose_name": "Телевизор Char",
                "verbose_name_plural": "Телевизоры Char",
            },
        ),
        migrations.CreateModel(
            name="TVSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model",
                    models.CharField(max_length=255, verbose_name="Модель телевизора"),
                ),
                (
                    "serial_number",
                    models.CharField(max_length=255, verbose_name="Серийный номер"),
                ),
                (
                    "screen_size",
                    models.CharField(max_length=50, verbose_name="Размер экрана"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="createdspek_tv",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Телевизор Спецификасии",
                "verbose_name_plural": "Телевизоры Спецификасии",
            },
        ),
    ]
