# Generated by Django 5.2 on 2025-05-16 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_alter_equipment_status_extenderchar_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MonoblokChar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cpu",
                    models.CharField(
                        help_text="Процессор", max_length=255, verbose_name="Процессор"
                    ),
                ),
                (
                    "ram",
                    models.CharField(
                        help_text="Оперативная память",
                        max_length=255,
                        verbose_name="Оперативная память",
                    ),
                ),
                (
                    "storage",
                    models.CharField(
                        help_text="Накопитель (SSD/HDD)",
                        max_length=255,
                        verbose_name="Накопитель",
                    ),
                ),
                (
                    "has_keyboard",
                    models.BooleanField(default=True, help_text="Есть ли клавиатура"),
                ),
                (
                    "has_mouse",
                    models.BooleanField(default=True, help_text="Есть ли мышь"),
                ),
                (
                    "monitor_size",
                    models.CharField(
                        blank=True,
                        help_text="Размер монитора (если есть)",
                        max_length=50,
                        verbose_name="Размер монитора",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="createChar_monoblok",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "equipment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monoblok_details",
                        to="inventory.equipment",
                        verbose_name="Моноблок",
                    ),
                ),
            ],
            options={
                "verbose_name": "Характеристика для Моноблока",
                "verbose_name_plural": "Характеристика для Моноблоков",
            },
        ),
        migrations.CreateModel(
            name="MonoblokSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cpu",
                    models.CharField(
                        help_text="Процессор", max_length=255, verbose_name="Процессор"
                    ),
                ),
                (
                    "ram",
                    models.CharField(
                        help_text="Оперативная память",
                        max_length=255,
                        verbose_name="Оперативная память",
                    ),
                ),
                (
                    "storage",
                    models.CharField(
                        help_text="Накопитель (SSD/HDD)",
                        max_length=255,
                        verbose_name="Накопитель",
                    ),
                ),
                (
                    "has_keyboard",
                    models.BooleanField(default=True, help_text="Есть ли клавиатура"),
                ),
                (
                    "has_mouse",
                    models.BooleanField(default=True, help_text="Есть ли мышь"),
                ),
                (
                    "monitor_size",
                    models.CharField(
                        blank=True,
                        help_text="Размер монитора (если есть)",
                        max_length=50,
                        verbose_name="Размер монитора",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="createdspek_monoblok",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Характеристика для Моноблока",
                "verbose_name_plural": "Характеристика для Моноблоков",
            },
        ),
        migrations.CreateModel(
            name="NotebookChar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cpu",
                    models.CharField(
                        help_text="Процессор", max_length=255, verbose_name="Процессор"
                    ),
                ),
                (
                    "ram",
                    models.CharField(
                        help_text="Оперативная память",
                        max_length=255,
                        verbose_name="Оперативная память",
                    ),
                ),
                (
                    "storage",
                    models.CharField(
                        help_text="Накопитель (SSD/HDD)",
                        max_length=255,
                        verbose_name="Накопитель",
                    ),
                ),
                (
                    "monitor_size",
                    models.CharField(
                        blank=True,
                        help_text="Размер монитора",
                        max_length=50,
                        verbose_name="Размер монитора",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="createdchar_notebook",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "equipment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notebook_details",
                        to="inventory.equipment",
                        verbose_name="Ноутбук",
                    ),
                ),
            ],
            options={
                "verbose_name": "Характеристики Ноутбука",
                "verbose_name_plural": "Характеристики Ноутбуков",
            },
        ),
        migrations.CreateModel(
            name="NotebookSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cpu",
                    models.CharField(
                        help_text="Процессор", max_length=255, verbose_name="Процессор"
                    ),
                ),
                (
                    "ram",
                    models.CharField(
                        help_text="Оперативная память",
                        max_length=255,
                        verbose_name="Оперативная память",
                    ),
                ),
                (
                    "storage",
                    models.CharField(
                        help_text="Накопитель (SSD/HDD)",
                        max_length=255,
                        verbose_name="Накопитель",
                    ),
                ),
                (
                    "monitor_size",
                    models.CharField(
                        blank=True,
                        help_text="Размер монитора",
                        max_length=50,
                        verbose_name="Размер монитора",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="createspek_notebook",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Характеристики Ноутбука",
                "verbose_name_plural": "Характеристики Ноутбуков",
            },
        ),
        migrations.CreateModel(
            name="ProjectorChar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=255, verbose_name="Модель")),
                (
                    "lumens",
                    models.PositiveIntegerField(verbose_name="Яркость (люмены)"),
                ),
                (
                    "resolution",
                    models.CharField(
                        help_text="Например, 1920x1080",
                        max_length=50,
                        verbose_name="Разрешение",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="createdchar_projector",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "equipment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projector_char",
                        to="inventory.equipment",
                        verbose_name="Оборудование",
                    ),
                ),
            ],
            options={
                "verbose_name": "Характеристики проектора",
                "verbose_name_plural": "Характеристики проекторов",
            },
        ),
        migrations.CreateModel(
            name="ProjectorSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=255, verbose_name="Модель")),
                (
                    "lumens",
                    models.PositiveIntegerField(verbose_name="Яркость (люмены)"),
                ),
                (
                    "resolution",
                    models.CharField(
                        help_text="Например, 1920x1080",
                        max_length=50,
                        verbose_name="Разрешение",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="createdspek_projector",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Шаблон проектора",
                "verbose_name_plural": "Шаблоны проекторов",
            },
        ),
        migrations.CreateModel(
            name="WhiteboardChar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=255, verbose_name="Модель")),
                (
                    "screen_size",
                    models.PositiveIntegerField(verbose_name="Размер экрана (дюймы)"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="createdchar_whiteboard",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "equipment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whiteboard_char",
                        to="inventory.equipment",
                        verbose_name="Оборудование",
                    ),
                ),
            ],
            options={
                "verbose_name": "Характеристики электронной доски",
                "verbose_name_plural": "Характеристики электронных досок",
            },
        ),
        migrations.CreateModel(
            name="WhiteboardSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=255, verbose_name="Модель")),
                (
                    "screen_size",
                    models.PositiveIntegerField(verbose_name="Размер экрана (дюймы)"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="createdspek_whiteboard",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Шаблон электронной доски",
                "verbose_name_plural": "Шаблоны электронных досок",
            },
        ),
    ]
