# Generated by Django 5.2 on 2025-05-17 07:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_monoblokchar_monoblokspecification_notebookchar_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notebookchar",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="notebookspecification",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="projectorchar",
            name="throw_type",
            field=models.CharField(
                choices=[
                    ("standard", "Стандартный"),
                    ("short", "Короткофокусный"),
                    ("ultra_short", "Ультракороткофокусный"),
                ],
                default=django.utils.timezone.now,
                max_length=20,
                verbose_name="Тип проекции",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="projectorspecification",
            name="throw_type",
            field=models.CharField(
                choices=[
                    ("standard", "Стандартный"),
                    ("short", "Короткофокусный"),
                    ("ultra_short", "Ультракороткофокусный"),
                ],
                default=django.utils.timezone.now,
                max_length=20,
                verbose_name="Тип проекции",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="whiteboardchar",
            name="touch_type",
            field=models.CharField(
                choices=[("infrared", "Инфракрасный"), ("capacitive", "Ёмкостный")],
                default=django.utils.timezone.now,
                max_length=20,
                verbose_name="Тип сенсора",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="whiteboardspecification",
            name="touch_type",
            field=models.CharField(
                choices=[("infrared", "Инфракрасный"), ("capacitive", "Ёмкостный")],
                default=django.utils.timezone.now,
                max_length=20,
                verbose_name="Тип сенсора",
            ),
            preserve_default=False,
        ),
    ]
