# Generated by Django 5.2 on 2025-05-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_notebookchar_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractdocument",
            name="valid_until",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата действия договора"
            ),
        ),
    ]
