# Generated by Django 5.2 on 2025-05-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_contractdocument_valid_until"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "Новое"),
                    ("WORKING", "Рабочее"),
                    ("NEEDS_REPAIR", "Требуется ремонт"),
                    ("DISPOSED", "Утилизировано"),
                ],
                default="NEW",
                max_length=20,
                verbose_name="Состояние",
            ),
        ),
    ]
