# Generated by Django 5.2 on 2025-06-08 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_computerspecification_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computerdetails',
            name='monitor_size',
        ),
        migrations.RemoveField(
            model_name='computerspecification',
            name='monitor_size',
        ),
        migrations.CreateModel(
            name='MonitorChar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255, verbose_name='Модель монитора')),
                ('serial_number', models.CharField(max_length=255, verbose_name='Серийный номер')),
                ('screen_size', models.CharField(max_length=50, verbose_name='Размер экрана')),
                ('resolution', models.CharField(help_text='Например, 1920x1080', max_length=50, verbose_name='Разрешение')),
                ('panel_type', models.CharField(blank=True, choices=[('IPS', 'IPS'), ('TN', 'TN'), ('VA', 'VA'), ('OLED', 'OLED')], max_length=20, verbose_name='Тип матрицы')),
                ('refresh_rate', models.PositiveIntegerField(blank=True, null=True, verbose_name='Частота обновления (Гц)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_monitor', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('equipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monitor_char', to='inventory.equipment', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'Монитор Char',
                'verbose_name_plural': 'Мониторы Char',
            },
        ),
        migrations.CreateModel(
            name='MonitorSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255, verbose_name='Модель монитора')),
                ('serial_number', models.CharField(max_length=255, verbose_name='Серийный номер')),
                ('screen_size', models.CharField(max_length=50, verbose_name='Размер экрана')),
                ('resolution', models.CharField(help_text='Например, 1920x1080', max_length=50, verbose_name='Разрешение')),
                ('panel_type', models.CharField(blank=True, choices=[('IPS', 'IPS'), ('TN', 'TN'), ('VA', 'VA'), ('OLED', 'OLED')], max_length=20, verbose_name='Тип матрицы')),
                ('refresh_rate', models.PositiveIntegerField(blank=True, null=True, verbose_name='Частота обновления (Гц)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdspek_monitor', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Спецификация монитора',
                'verbose_name_plural': 'Спецификации мониторов',
            },
        ),
    ]
