# Generated by Django 5.2 on 2025-06-08 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_remove_computerdetails_monitor_size_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(help_text='Модель видеокарты', max_length=255, verbose_name='Модель')),
                ('memory_gb', models.IntegerField(help_text='Объем видеопамяти в ГБ', verbose_name='Объем памяти (ГБ)')),
                ('memory_type', models.CharField(blank=True, help_text='Тип памяти (GDDR5, GDDR6, etc.)', max_length=50, verbose_name='Тип памяти')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_gpus', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gpus', to='inventory.equipment', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'Видеокарта',
                'verbose_name_plural': 'Видеокарты',
            },
        ),
        migrations.CreateModel(
            name='GPUSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(help_text='Модель видеокарты', max_length=255, verbose_name='Модель')),
                ('memory_gb', models.IntegerField(help_text='Объем видеопамяти в ГБ', verbose_name='Объем памяти (ГБ)')),
                ('memory_type', models.CharField(blank=True, help_text='Тип памяти (GDDR5, GDDR6, etc.)', max_length=50, verbose_name='Тип памяти')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_gpu_specs', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('computer_specification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gpu_specifications', to='inventory.computerspecification')),
                ('monoblok_specification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gpu_specifications', to='inventory.monoblokspecification')),
                ('notebook_specification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gpu_specifications', to='inventory.notebookspecification')),
            ],
            options={
                'verbose_name': 'Спецификация видеокарты',
                'verbose_name_plural': 'Спецификации видеокарт',
            },
        ),
    ]
