# Generated by Django 5.2 on 2025-06-08 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_gpu_gpuspecification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpu',
            name='memory_gb',
        ),
        migrations.RemoveField(
            model_name='gpu',
            name='memory_type',
        ),
        migrations.RemoveField(
            model_name='gpuspecification',
            name='memory_gb',
        ),
        migrations.RemoveField(
            model_name='gpuspecification',
            name='memory_type',
        ),
        migrations.AddField(
            model_name='computerspecification',
            name='gpus',
            field=models.ManyToManyField(blank=True, to='inventory.gpuspecification', verbose_name='Видеокарты'),
        ),
        migrations.AddField(
            model_name='monoblokspecification',
            name='gpus',
            field=models.ManyToManyField(blank=True, to='inventory.gpuspecification', verbose_name='Видеокарты'),
        ),
        migrations.AddField(
            model_name='notebookspecification',
            name='gpus',
            field=models.ManyToManyField(blank=True, to='inventory.gpuspecification', verbose_name='Видеокарты'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='model',
            field=models.CharField(max_length=255, verbose_name='Модель видеокарты'),
        ),
        migrations.AlterField(
            model_name='gpuspecification',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_gpu_specifications', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='gpuspecification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='gpuspecification',
            name='model',
            field=models.CharField(max_length=255, verbose_name='Модель видеокарты'),
        ),
    ]
