# Generated by Django 5.2 on 2025-05-10 12:31

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("admin", "Администратор"), ("manager", "Менеджер")],
                        default="manager",
                        max_length=10,
                        verbose_name="Роль",
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=150, unique=True, verbose_name="Логин"),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=100, verbose_name="Фамилия")),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Телефонный номер",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Электронная почта"
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="profile_pics/",
                        verbose_name="Фото профиля",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="SupportMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=255, verbose_name="Тема")),
                ("message", models.TextField(verbose_name="Сообщение")),
                (
                    "sent_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время отправки"
                    ),
                ),
                (
                    "is_resolved",
                    models.BooleanField(default=False, verbose_name="Решено"),
                ),
                ("is_notified", models.BooleanField(default=False)),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Отправитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сообщение в поддержку",
                "verbose_name_plural": "Сообщения в поддержку",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.CreateModel(
            name="UserAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("CREATE", "Создание"),
                            ("UPDATE_INN", "Обновление ИНН"),
                            ("MOVE", "Перемещение"),
                            ("DELETE", "Удаление"),
                            ("CREATE_ROOM", "Создание кабинета"),
                            ("DELETE_ROOM", "Удаление кабинета"),
                            ("CREATE_EQUIPMENT", "Создание оборудования"),
                            ("UPDATE_EQUIPMENT", "Обновление оборудования"),
                            ("DELETE_EQUIPMENT", "Удаление оборудования"),
                            ("CREATE_USER", "Создание пользователя"),
                            ("UPDATE_USER", "Обновление пользователя"),
                            ("DELETE_USER", "Удаление пользователя"),
                            (
                                "CREATE_SUPPORT_MESSAGE",
                                "Создание сообщения в поддержку",
                            ),
                            (
                                "UPDATE_SUPPORT_MESSAGE",
                                "Обновление сообщения в поддержку",
                            ),
                            (
                                "DELETE_SUPPORT_MESSAGE",
                                "Удаление сообщения в поддержку",
                            ),
                            ("CREATE_BUILDING", "Создание здания"),
                            ("DELETE_BUILDING", "Удаление здания"),
                            ("CREATE_FLOOR", "Создание этажа"),
                            ("CREATE_FACILITY", "Создание факультета"),
                            ("DELETE_FLOOR", "Удаление этажа"),
                            ("DELETE_FACILITY", "Удаление факультета"),
                        ],
                        max_length=22,
                    ),
                ),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Действие пользователя",
                "verbose_name_plural": "Действия пользователей",
                "ordering": ["-created_at"],
            },
        ),
    ]
