# Generated by Django 5.2 on 2025-06-06 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraction",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
                verbose_name="Тип объекта",
            ),
        ),
        migrations.AddField(
            model_name="useraction",
            name="details",
            field=models.JSONField(blank=True, null=True, verbose_name="Детали"),
        ),
        migrations.AddField(
            model_name="useraction",
            name="new_value",
            field=models.TextField(
                blank=True, null=True, verbose_name="Новое значение"
            ),
        ),
        migrations.AddField(
            model_name="useraction",
            name="object_id",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="ID объекта"
            ),
        ),
        migrations.AddField(
            model_name="useraction",
            name="old_value",
            field=models.TextField(
                blank=True, null=True, verbose_name="Старое значение"
            ),
        ),
        migrations.AlterField(
            model_name="useraction",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("CREATE", "Создание"),
                    ("UPDATE_INN", "Обновление ИНН"),
                    ("MOVE", "Перемещение"),
                    ("DELETE", "Удаление"),
                    ("CREATE_ROOM", "Создание кабинета"),
                    ("DELETE_ROOM", "Удаление кабинета"),
                    ("CREATE_EQUIPMENT", "Создание оборудования"),
                    ("UPDATE_EQUIPMENT", "Обновление оборудования"),
                    ("DELETE_EQUIPMENT", "Удаление оборудования"),
                    ("CREATE_USER", "Создание пользователя"),
                    ("UPDATE_USER", "Обновление пользователя"),
                    ("DELETE_USER", "Удаление пользователя"),
                    ("CREATE_SUPPORT_MESSAGE", "Создание сообщения в поддержку"),
                    ("UPDATE_SUPPORT_MESSAGE", "Обновление сообщения в поддержку"),
                    ("DELETE_SUPPORT_MESSAGE", "Удаление сообщения в поддержку"),
                    ("CREATE_BUILDING", "Создание здания"),
                    ("DELETE_BUILDING", "Удаление здания"),
                    ("CREATE_FLOOR", "Создание этажа"),
                    ("CREATE_FACILITY", "Создание факультета"),
                    ("DELETE_FLOOR", "Удаление этажа"),
                    ("DELETE_FACILITY", "Удаление факультета"),
                    ("SCAN", "Сканирование QR-кода"),
                    ("CREATE_REPAIR", "Создание записи о ремонте"),
                    ("UPDATE_REPAIR", "Обновление записи о ремонте"),
                    ("CREATE_DISPOSAL", "Создание записи об утилизации"),
                    ("UPDATE_DISPOSAL", "Обновление записи об утилизации"),
                    ("SEND_TO_REPAIR", "Отправка оборудования на ремонт"),
                    ("DISPOSE_EQUIPMENT", "Утилизация оборудования"),
                ],
                max_length=30,
            ),
        ),
    ]
