# Generated by Django 5.2 on 2025-06-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_useraction_content_type_useraction_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plain_password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Исходный пароль'),
        ),
    ]
