# Generated by Django 5.2 on 2025-05-10 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название корпуса"),
                ),
                ("address", models.TextField(blank=True, verbose_name="Адрес корпуса")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="building_photos/",
                        verbose_name="Фото корпуса",
                    ),
                ),
            ],
            options={
                "verbose_name": "Корпус",
                "verbose_name_plural": "Корпуса",
            },
        ),
        migrations.CreateModel(
            name="University",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Название университета"
                    ),
                ),
                ("address", models.TextField(verbose_name="Адрес")),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="university_logos/",
                        verbose_name="Логотип",
                    ),
                ),
            ],
            options={
                "verbose_name": "Университет",
                "verbose_name_plural": "Университеты",
            },
        ),
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Название факультета"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="faculty_photos/",
                        verbose_name="Фото факультета",
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faculties",
                        to="university.building",
                        verbose_name="Корпус",
                    ),
                ),
            ],
            options={
                "verbose_name": "Факультет",
                "verbose_name_plural": "Факультеты",
            },
        ),
        migrations.CreateModel(
            name="FacultyHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=100, verbose_name="Действие")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Время"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="histories",
                        to="university.faculty",
                        verbose_name="Факультет",
                    ),
                ),
            ],
            options={
                "verbose_name": "История факультета",
                "verbose_name_plural": "Истории факультетов",
            },
        ),
        migrations.CreateModel(
            name="Floor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(verbose_name="Номер этажа")),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Описание (необязательно)"
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="floors",
                        to="university.building",
                        verbose_name="Корпус",
                    ),
                ),
            ],
            options={
                "verbose_name": "Этаж",
                "verbose_name_plural": "Этажи",
                "unique_together": {("building", "number")},
            },
        ),
        migrations.AddField(
            model_name="faculty",
            name="floor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="faculties",
                to="university.floor",
                verbose_name="Этаж",
            ),
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(max_length=20, verbose_name="Номер кабинета"),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Название (если есть)"
                    ),
                ),
                (
                    "is_special",
                    models.BooleanField(
                        default=False, verbose_name="Специальный кабинет"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="room_photos/",
                        verbose_name="Фото кабинета",
                    ),
                ),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="room_qrcodes/",
                        verbose_name="QR-код кабинета",
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="university.building",
                        verbose_name="Корпус",
                    ),
                ),
                (
                    "derived_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="derived_rooms",
                        to="university.room",
                        verbose_name="Создан из кабинета",
                    ),
                ),
                (
                    "floor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="university.floor",
                        verbose_name="Этаж",
                    ),
                ),
            ],
            options={
                "verbose_name": "Кабинет",
                "verbose_name_plural": "Кабинеты",
                "unique_together": {("floor", "number")},
            },
        ),
        migrations.CreateModel(
            name="RoomHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=100)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField(blank=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="histories",
                        to="university.room",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="building",
            name="university",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buildings",
                to="university.university",
                verbose_name="Университет",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="faculty",
            unique_together={("building", "name")},
        ),
    ]
